In [2]:
import tensorflow as tf
import numpy as np
import cv2 
import pathlib

2024-03-21 21:41:35.180943: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-21 21:41:35.219132: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-21 21:41:35.219178: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-21 21:41:35.220386: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-21 21:41:35.226602: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-21 21:41:35.227706: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [3]:
model = tf.keras.models.load_model("Model/2")

In [5]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 sequential (Sequential)     (None, 256, 256, 3)       0         
                                                                 
 sequential_1 (Sequential)   (None, 256, 256, 3)       0         
                                                                 
 conv2d (Conv2D)             (None, 256, 256, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2  (None, 128, 128, 32)      0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 128, 128, 64)      18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 64, 64, 64)        0         
 g2D)                                                 

In [16]:
test_data = pathlib.Path('test_images')
test_data

PosixPath('test_images')

In [22]:
predicting_images_paths = list(test_data.glob('*'))
predicting_images_paths

[PosixPath('test_images/EarlyBlight.webp'),
 PosixPath('test_images/healthy2.webp'),
 PosixPath('test_images/testhealth.jpg')]

In [25]:
predicting_images, names = [],[]

for i in predicting_images_paths:
    image = cv2.imread(str(i))
    print(image)
    predicting_images.append(image)
    names.append(str(i))

names

[[[ 84 152 173]
  [ 84 152 173]
  [ 84 152 173]
  ...
  [ 76 122 141]
  [ 71 114 134]
  [ 66 109 130]]

 [[ 84 152 173]
  [ 84 152 173]
  [ 84 152 173]
  ...
  [ 79 125 145]
  [ 73 116 137]
  [ 69 112 132]]

 [[ 85 153 174]
  [ 85 153 174]
  [ 85 153 174]
  ...
  [ 83 128 148]
  [ 78 121 141]
  [ 73 116 137]]

 ...

 [[  4  11  12]
  [  3  10  11]
  [  3  10  11]
  ...
  [ 16  27  34]
  [ 16  27  34]
  [ 16  27  34]]

 [[  4  11  12]
  [  3  10  11]
  [  3  10  11]
  ...
  [ 17  28  36]
  [ 17  28  36]
  [ 17  28  36]]

 [[  8  12  13]
  [  6  10  12]
  [  4   8  10]
  ...
  [ 17  29  34]
  [ 17  29  34]
  [ 17  29  34]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..

['test_images/EarlyBlight.webp',
 'test_images/healthy2.webp',
 'test_images/testhealth.jpg']

In [36]:
def image_calling(i):
    image = predicting_images[i]
    resizing = np.array(cv2.resize(image,(256,256)))
    expanding = np.expand_dims(resizing,0)
    return expanding


In [39]:
predicting_image = image_calling(1)
predicting_image

array([[[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
        

In [42]:

np.argmax(model.predict(predicting_image))

1/1 [==============================] - 0s 29ms/step


2

In [43]:
names[1]

'test_images/healthy2.webp'

Dataset Labels
    "Potato Early Blight" : 0,
    "Potato Late Blight" : 1,
    "Healthy" : 2